const plural = (n: number, one: string, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;

export const controlCopy = {
  title: "Control panel",
  passcodeLabel: "Passcode",
  unlock: "Unlock",
  lock: "Lock",
  tabs: { queue: "Queue", photos: "Photos", remote: "Remote", overview: "Overview" },
  status: { approved: "On wall", pending: "Pending", hidden: "Hidden" },
  remote: {
    hint: "Controls every screen showing the wall.",
    left: "Previous photo",
    right: "Next photo",
    select: "Open or close full screen",
    back: "Close full screen",
    playpause: "Pause or resume",
  },
  queue: {
    approve: "Approve",
    approving: "Approving…",
    reject: "Reject",
    rejecting: "Rejecting…",
    approveAll: (n: number) => `Approve all ${n}`,
    approvingAll: (done: number, total: number) => `Approving ${done + 1} of ${total}…`,
    confirmApproveAll: (n: number) => `Put all ${n} waiting photos on the wall?`,
    empty: "All caught up — nothing waiting.",
  },
  photos: {
    search: "Search captions",
    clearSearch: "Clear search",
    statusFilter: "Status",
    allStatuses: "All",
    category: "Category",
    allCategories: "All categories",
    sort: "Sort",
    sorts: { newest: "Newest", oldest: "Oldest", category: "Category" },
    select: "Select",
    done: "Done",
    selectPhoto: (caption: string) => `Select ${caption}`,
    openPhoto: (caption: string) => `Open ${caption}`,
    count: (n: number, more: boolean) => `${n}${more ? "+" : ""} ${n === 1 ? "photo" : "photos"}`,
    loadMore: "Load more",
    loadingMore: "Loading…",
    empty: "No photos yet. They show up here as soon as someone uploads one.",
    emptyFiltered: "No photos match these filters.",
    clearFilters: "Clear filters",
    loadFailed: "Couldn't load the photos.",
    retry: "Try again",
    refresh: "Refresh",
  },
  bulk: {
    selected: (n: number) => `${n} selected`,
    selectAll: "Select all",
    hide: "Hide",
    show: "Show",
    delete: "Delete",
    working: (verb: string, done: number, total: number) =>
      `${verb} ${Math.min(done + 1, total)} of ${total}…`,
    verbs: { hide: "Hiding", show: "Showing", delete: "Deleting" },
    confirmDelete: (n: number) => `Delete ${plural(n, "photo")}?`,
    confirmHide: (n: number) => `Hide ${plural(n, "photo")} from the wall?`,
    confirmShow: (n: number) => `Put ${plural(n, "photo")} on the wall?`,
    done: {
      hide: (n: number) => `${plural(n, "photo")} hidden.`,
      show: (n: number) => `${plural(n, "photo")} on the wall.`,
      delete: (n: number) => `${plural(n, "photo")} deleted.`,
    },
    failed: (done: number, total: number) => `Stopped after ${done} of ${total}. Try again.`,
  },
  sheet: {
    title: "Photo",
    close: "Close",
    caption: "Caption",
    captionHint: (left: number) => `${left} characters left`,
    category: "Category",
    save: "Save changes",
    saving: "Saving…",
    approve: "Approve",
    hide: "Hide from wall",
    show: "Show on wall",
    delete: "Delete",
    openLarge: "Open large",
    uploaded: (when: string) => `Uploaded ${when}`,
  },
  confirm: {
    cancel: "Cancel",
    delete: "Delete",
    deleteOne: "Delete this photo?",
    deleteBody: "It's removed from the wall and storage. This can't be undone.",
    hideBody: "They stay in Photos, so you can show them again later.",
    showBody: "They appear on every wall screen straight away.",
    confirm: "Confirm",
  },
  toast: {
    hidden: "Hidden from the wall.",
    shown: "Back on the wall.",
    approved: "On the wall.",
    saved: "Saved.",
    deleted: "Deleted.",
    undo: "Undo",
    failed: "That didn't work. Try again.",
  },
  overview: {
    onWall: "On the wall",
    pending: "Waiting",
    hidden: "Hidden",
    uploadsToday: "Uploads today",
    byCategory: "By category",
    legend: { onWall: "on wall", pending: "waiting", hidden: "hidden" },
    categoryLine: (onWall: number, pending: number, hidden: number) =>
      `${onWall} on wall, ${pending} waiting, ${hidden} hidden`,
    loadFailed: "Couldn't load the numbers. Retrying…",
  },
  photoAlt: "Submitted photo",
  noCaption: "No caption",
  badPasscode: "Wrong passcode.",
  locked: "Too many wrong passcodes. Try again in 15 minutes.",
  loadFailed: "Couldn't reach the wall. Retrying…",
} as const;
