export const adminCopy = {
  title: "Booth control",
  passcodeLabel: "Passcode",
  unlock: "Unlock",
  lock: "Lock",
  tabs: { pending: "Waiting", approved: "On the wall", remote: "Remote" },
  remote: {
    hint: "Controls every screen showing the wall.",
    left: "Previous photo",
    right: "Next photo",
    select: "Open or close full screen",
    back: "Close full screen",
    playpause: "Pause or resume",
  },
  approve: "Approve",
  reject: "Reject",
  remove: "Remove",
  confirmRemove: "Take this photo off the wall?",
  emptyPending: "All caught up — nothing waiting.",
  emptyApproved: "Nothing on the wall yet.",
  badPasscode: "Wrong passcode.",
  locked: "Too many wrong passcodes. Try again in 15 minutes.",
  loadFailed: "Couldn't reach the wall. Retrying…",
} as const;
